//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_architecture_35.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVC_architecture_35.Language.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADMIN.
        /// </summary>
        internal static string adminBtn {
            get {
                return ResourceManager.GetString("adminBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age:.
        /// </summary>
        internal static string ageLabel {
            get {
                return ResourceManager.GetString("ageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACK.
        /// </summary>
        internal static string backBtn {
            get {
                return ResourceManager.GetString("backBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string clearBtn {
            get {
                return ResourceManager.GetString("clearBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an Account.
        /// </summary>
        internal static string createAccountTxt {
            get {
                return ResourceManager.GetString("createAccountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and Edit players.
        /// </summary>
        internal static string editPlayerTitle {
            get {
                return ResourceManager.GetString("editPlayerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string emailLabel {
            get {
                return ResourceManager.GetString("emailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string french {
            get {
                return ResourceManager.GetString("french", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name:.
        /// </summary>
        internal static string fullNameLabel {
            get {
                return ResourceManager.GetString("fullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow Puzzle Game.
        /// </summary>
        internal static string gameTitle {
            get {
                return ResourceManager.GetString("gameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - You have to place arrows strategically on the grid to fill it without having two arrows.
        /// </summary>
        internal static string homeText11 {
            get {
                return ResourceManager.GetString("homeText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the same color pointing in the same direction along any row, column, or diagonal..
        /// </summary>
        internal static string homeText12 {
            get {
                return ResourceManager.GetString("homeText12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Each player takes turns placing arrows on empty cells of the grid aiming to create a.
        /// </summary>
        internal static string homeText21 {
            get {
                return ResourceManager.GetString("homeText21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pattern that adheres to the rule mentioned above..
        /// </summary>
        internal static string homeText22 {
            get {
                return ResourceManager.GetString("homeText22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - The game ends when one player can no longer make a legal move, resulting in their.
        /// </summary>
        internal static string homeText31 {
            get {
                return ResourceManager.GetString("homeText31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opponent winning.
        /// </summary>
        internal static string hometext32 {
            get {
                return ResourceManager.GetString("hometext32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Arrow Puzzle Game.
        /// </summary>
        internal static string homeTitle {
            get {
                return ResourceManager.GetString("homeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        internal static string levelLabel {
            get {
                return ResourceManager.GetString("levelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        internal static string loginBtn {
            get {
                return ResourceManager.GetString("loginBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string loginText1 {
            get {
                return ResourceManager.GetString("loginText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I just want to play the game!.
        /// </summary>
        internal static string loginText2 {
            get {
                return ResourceManager.GetString("loginText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string loginTitle {
            get {
                return ResourceManager.GetString("loginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginTxt {
            get {
                return ResourceManager.GetString("loginTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oponent moves:.
        /// </summary>
        internal static string opoMovesLabel {
            get {
                return ResourceManager.GetString("opoMovesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oponent score:.
        /// </summary>
        internal static string opoScoreLabel {
            get {
                return ResourceManager.GetString("opoScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string passwordLabel {
            get {
                return ResourceManager.GetString("passwordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayerID:.
        /// </summary>
        internal static string playerdIDLabel {
            get {
                return ResourceManager.GetString("playerdIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY  GAME.
        /// </summary>
        internal static string playGameBtn {
            get {
                return ResourceManager.GetString("playGameBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Game.
        /// </summary>
        internal static string playGameTxt {
            get {
                return ResourceManager.GetString("playGameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your moves:.
        /// </summary>
        internal static string plyMovesLabel {
            get {
                return ResourceManager.GetString("plyMovesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your score:.
        /// </summary>
        internal static string plyScoreLabel {
            get {
                return ResourceManager.GetString("plyScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Score:.
        /// </summary>
        internal static string savedScoreLabel {
            get {
                return ResourceManager.GetString("savedScoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:.
        /// </summary>
        internal static string scoreLabel {
            get {
                return ResourceManager.GetString("scoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH.
        /// </summary>
        internal static string searchBtn {
            get {
                return ResourceManager.GetString("searchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN OUT.
        /// </summary>
        internal static string signOutBtn {
            get {
                return ResourceManager.GetString("signOutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNUP.
        /// </summary>
        internal static string signUpBtn {
            get {
                return ResourceManager.GetString("signUpBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        internal static string signUpText {
            get {
                return ResourceManager.GetString("signUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        internal static string signUpTitle {
            get {
                return ResourceManager.GetString("signUpTitle", resourceCulture);
            }
        }
    }
}
